<a href="https://colab.research.google.com/github/BrunaMoraisMenezesDSM/FATEC_MINERACAO_DADOS_2SEM2024/blob/master/Aula01_Demonstra%C3%A7%C3%A3o_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Demonstração da Biblioteca Numpy**

# Importação da Biblioteca

In [1]:
import numpy as np

# Gerar alguns dados aleatórios

Gerar um ndarray 2x3 - duas listas com 3 elementos

lista1 = [1,2,3]

lista2 = [4,5,6]

In [2]:
dados = np.random.rand(2,3)

In [3]:
dados

array([[0.10350753, 0.9246884 , 0.68169257],
       [0.83978098, 0.86294798, 0.91180801]])

# Verificando o tipo do Array

In [4]:
dados.dtype

dtype('float64')

# Verificar Tamanho e Quantidade de Dimensões

In [5]:
dados.shape

(2, 3)

In [6]:
dados.ndim

2

# Criando um ndarray a partir de uma estrutura básica python - Ex. Listas

In [7]:
lista = [1,2,3,4,5]

In [8]:
dados1 = np.array(lista)

In [9]:
dados1

array([1, 2, 3, 4, 5])

In [10]:
lista2 = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
dados2 = np.array(lista2)

In [12]:
dados2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Transfomando tipos

In [13]:
dados3 = np.array([[1,2,3],[4,5,6]])
dados3

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
dados3_novo = dados3.astype(np.float64)
dados3_novo

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
dados3.dtype

dtype('int64')

In [16]:
dados3_novo.dtype

dtype('float64')

# Aritmética com Arrays

In [17]:
dados4 = np.array([[1,2,3],[4,5,6]])
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
dados5 = np.array([[7,8,9],[10,11,12]])
dados5

array([[ 7,  8,  9],
       [10, 11, 12]])

In [19]:
dados5[1,1]

11

In [20]:
resultado = dados4 * dados5
resultado

array([[ 7, 16, 27],
       [40, 55, 72]])

# Indexação

In [21]:
exemplo = [1,2,3,4,5]
exemplo[2]

3

In [22]:
dadosseq = np.array([1,2,3,4,5,6])
dadosseq

array([1, 2, 3, 4, 5, 6])

In [23]:
dadosseq[4]

5

# Fatias

In [24]:
dadosseq[2:4]

array([3, 4])

In [25]:
x = dadosseq[2:4]

In [26]:
x

array([3, 4])

In [27]:
dadosseq

array([1, 2, 3, 4, 5, 6])

# Alterando um valor dentro de um nparray

In [28]:
dadosseq[2] = 11111
dadosseq

array([    1,     2, 11111,     4,     5,     6])

# Máscaras

In [29]:
fatia = dadosseq[2:4]
fatia
fatia[fatia < 10] = 50
fatia

array([11111,    50])

In [30]:
dadosseq

array([    1,     2, 11111,    50,     5,     6])

# Transposição

In [31]:
dados5

array([[ 7,  8,  9],
       [10, 11, 12]])

In [32]:
dados5.T

array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]])

In [33]:
dados5

array([[ 7,  8,  9],
       [10, 11, 12]])

In [34]:
transposta = dados5.T


In [35]:
transposta

array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]])

# Multiplicação de Matrizes com dots

In [36]:
np.dot(dados5,transposta)

array([[194, 266],
       [266, 365]])